#!/bin/bash
#
#  curl commands to reload the data from the previous tutorial
#
#
set -e

printf "⏳ Loading context data "

#
# Create four Store Entities in various locations across Berlin
#

curl -s -o /dev/null -X POST \
  'http://'$ORION_HOST':'$ORION_PORT'/v2/entities' \
  -H 'Content-Type: application/json' \
  -H 'fiware-service: openiot' \
  -H 'fiware-servicepath: /' \
  -d '{
      "id": "urn:ngsi-ld:Store:001",
      "type": "Store",
      "address": {
            "type": "PostalAddress",
            "value": {
                  "streetAddress": "Bornholmer Straße 65",
                  "addressRegion": "Berlin",
                  "addressLocality": "Prenzlauer Berg",
                  "postalCode": "10439"
            }
      },
      "location": {
            "type": "geo:json",
            "value": {
                  "type": "Point",
                  "coordinates": [
                        13.3986,
                        52.5547
                  ]
            }
      },
      "name": {
            "type": "Text",
            "value": "Bösebrücke Einkauf"
      }
}'

echo -e " \033[1;32mdone\033[0m"