apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:1.18.0
        imagePullPolicy: Always
        name: nginx
        ports:
          - name: api-crate
            containerPort: 8080
        resources: {}
        volumeMounts:
          - name: nginx-conf
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
          - name: nginx-dh
            mountPath: /certs/dhparam.pem
            subPath: dhparam.pem
          - name: nginx-selfsigned-crt
            mountPath: /certs/nginx-selfsigned.crt
            subPath: nginx-selfsigned.crt
          - name: nginx-selfsigned-key
            mountPath: /certs/nginx-selfsigned.key
            subPath: nginx-selfsigned.key
      # Load the configuration files for nginx
      restartPolicy: Always
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
        - name: nginx-dh
          configMap:
            name: nginx-dh
        - name: nginx-selfsigned-crt
          configMap:
            name: nginx-selfsigned-crt
        - name: nginx-selfsigned-key
          configMap:
            name: nginx-selfsigned-key