apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/kompose-default: "true"
        io.kompose.service: nginx
    spec:
      containers:
      - image: nginx:1.18.0
        imagePullPolicy: Always
        name: nginx
        ports:
          - name: api-crate
            containerPort: 8080
        resources: {}
        volumeMounts:
          - name: nginx-conf
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
          - name: nginx-dh
            mountPath: /certs/dhparam.pem
            subPath: dhparam.pem
          - name: nginx-selfsigned-crt
            mountPath: /certs/nginx-selfsigned.crt
            subPath: nginx-selfsigned.crt
          - name: nginx-selfsigned-key
            mountPath: /certs/nginx-selfsigned.key
            subPath: nginx-selfsigned.key
      # Load the configuration files for nginx
      restartPolicy: Always
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
        - name: nginx-dh
          configMap:
            name: nginx-dh
        - name: nginx-selfsigned-crt
          configMap:
            name: nginx-selfsigned-crt
        - name: nginx-selfsigned-key
          configMap:
            name: nginx-selfsigned-key
status: {}