apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
  type: NodePort
  - name: api-crate
    protocol: TCP
    port: 4430
    targetPort: 8080
    nodePort: 30080
  selector:
    app: nginx
status:
  loadBalancer: {}